### ISSUE TITLE
add control entity delegates

### ISSUE THREAD

**Issue by Pirates-of-Fife** [Pirates-of-Fife/oddity#110]
This should allow a control entity to be controlled by another control entity, aka a control seat. E.g.: This will allow a vehicle to be driven or controlled from multiple positions.

**Comment by ZoeMcFife** [comment]
basically implements #111. will merge and continue working on the control seat class. The delegates and stuff are useless, since a control seat doesn't need to be a control entity itself, just has to have an anchor.
